### ISSUE TITLE
d3-sankey is in a private repository.

### ISSUE THREAD

**Issue by webgem-jpl** [openculinary/frontend#185] opened 2020-12-25 17:49 UTC
**Describe the bug**
It is currently impossible to install node.js dependencies because "d3-sankey" is from a private repository.

**To Reproduce**
1. Without access to: "github:jayaddison"
2. npm install --also=dev

**Expected behavior**
All node.js dependencies should be installable.

**Comment by jayaddison** [comment] 2020-12-28 12:09
Hi @webgem-jpl - the [package dependency on `jayaddison/d3-sankey`](https://github.com/openculinary/frontend/blob/5c8f9c19d80905df785a1b4c8501cc192ebfcf6b/package.json#L11) refers to a [public fork](https://github.com/jayaddison/d3-sankey) of the original [`d3-sankey`](https://github.com/d3/d3-sankey), so I'm surprised it appears private to you - can you provide a few more details?

**Comment by jayaddison** [comment] 2021-01-23 14:16
Closing this for now; please feel free to comment with more details and re-open if the installation issue's still occurring.

**Comment by jayaddison** [comment] 2021-01-24 14:40
This issue has been verified; basically it turns out that this appears as an `npm` install-time error message indicating a possible permissions/access issue.

I think we'll be able to switch back to using an HTTPS-based repository clone approach.

**Closed** 2021-01-24 14:44 UTC
Labels: bug

**Comment by jayaddison** [comment] 2021-01-24 15:26
@webgem-jpl fwiw, I think https://github.com/npm/cli/issues/2389 is the upstream issue for this if you'd like to follow resolution

**Comment by jayaddison** [comment] 2021-01-24 20:07
Just to clarify a little for the record: the issue isn't that this `frontend` repository is private; it's not, or certainly shouldn't be - it's a public repository.

The issue is that `npm` is attempting to use SSH key-based authentication (instead of anonymous HTTPS access) via `git` when retrieving the `d3-sankey` module contents from the repository.  This leads to problems on systems that do not have SSH client authentication keys configured for requests to GitHub.

One alternative would be to post a version of `d3-sankey` to the NPM package repository under an alternate name, but generally that seems like it could mislead people; I'd prefer if we could upstream the fixes required to render sankey diagrams vertically and then upgrade to use an officially-packaged release of `d3-sankey`.
